var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/upload-frame-template/route.js")
R.c("server/chunks/node_modules_next_82cad45e._.js")
R.c("server/chunks/node_modules_xmlbuilder_lib_bfb18792._.js")
R.c("server/chunks/node_modules_minio_dist_esm_e99ac291._.js")
R.c("server/chunks/node_modules_async_dist_async_mjs_3c3c2e3f._.js")
R.c("server/chunks/node_modules_lodash_lodash_1b8cfecf.js")
R.c("server/chunks/cf60e_mime-db_c6ce8e3d._.js")
R.c("server/chunks/node_modules_@auth_core_36df0127._.js")
R.c("server/chunks/node_modules_jose_dist_webapi_911f8e7d._.js")
R.c("server/chunks/node_modules_52706afc._.js")
R.c("server/chunks/[root-of-the-server]__96fb12b2._.js")
R.m("[project]/.next-internal/server/app/api/upload-frame-template/route/actions.js [app-rsc] (server actions loader, ecmascript)")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/upload-frame-template/route.js [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/upload-frame-template/route.js [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
