// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/frame-template" | "/admin/frame-template/list" | "/admin/sticker" | "/admin/sticker/list" | "/admin/sticker/new" | "/auth/signin" | "/auth/signup" | "/photo" | "/photo/edit" | "/photo/gallery" | "/photo/gallery/[id]" | "/photo/upload" | "/photo/uploaded"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/auth/register" | "/api/delete-frame-template" | "/api/delete-photo" | "/api/delete-sticker" | "/api/gallery" | "/api/gallery/[id]" | "/api/get-presigned-url" | "/api/image-proxy" | "/api/list-frame-template" | "/api/list-sticker" | "/api/minio-proxy" | "/api/sticker-search" | "/api/test-minio-url" | "/api/update-frame-template" | "/api/update-sticker" | "/api/upload-captured-photo" | "/api/upload-frame-sticker" | "/api/upload-frame-template" | "/api/upload-sticker" | "/api/upload-strip" | "/photo-result"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/frame-template": {}
  "/admin/frame-template/list": {}
  "/admin/sticker": {}
  "/admin/sticker/list": {}
  "/admin/sticker/new": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/register": {}
  "/api/delete-frame-template": {}
  "/api/delete-photo": {}
  "/api/delete-sticker": {}
  "/api/gallery": {}
  "/api/gallery/[id]": { "id": string; }
  "/api/get-presigned-url": {}
  "/api/image-proxy": {}
  "/api/list-frame-template": {}
  "/api/list-sticker": {}
  "/api/minio-proxy": {}
  "/api/sticker-search": {}
  "/api/test-minio-url": {}
  "/api/update-frame-template": {}
  "/api/update-sticker": {}
  "/api/upload-captured-photo": {}
  "/api/upload-frame-sticker": {}
  "/api/upload-frame-template": {}
  "/api/upload-sticker": {}
  "/api/upload-strip": {}
  "/auth/signin": {}
  "/auth/signup": {}
  "/photo": {}
  "/photo-result": {}
  "/photo/edit": {}
  "/photo/gallery": {}
  "/photo/gallery/[id]": { "id": string; }
  "/photo/upload": {}
  "/photo/uploaded": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
