var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/list-sticker/route.js")
R.c("server/chunks/node_modules_next_5c828f5c._.js")
R.c("server/chunks/node_modules_xmlbuilder_lib_bfb18792._.js")
R.c("server/chunks/node_modules_minio_dist_esm_e99ac291._.js")
R.c("server/chunks/node_modules_async_dist_async_mjs_3c3c2e3f._.js")
R.c("server/chunks/node_modules_lodash_lodash_1b8cfecf.js")
R.c("server/chunks/cf60e_mime-db_c6ce8e3d._.js")
R.c("server/chunks/node_modules_ef4caa95._.js")
R.c("server/chunks/[root-of-the-server]__67d4e443._.js")
R.m("[project]/.next-internal/server/app/api/list-sticker/route/actions.js [app-rsc] (server actions loader, ecmascript)")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/list-sticker/route.js [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/list-sticker/route.js [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
